# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.

"""Per-conversation runtime factories and explicit main/child recipes.

Prepared shares the client, stateless tools, MCP adapter and skills index.
Context-management tools are generated by each private ContextManager, never
included in SharedRuntime. Recipes retain each shell's context and chat order;
callbacks here are bound to one conversation, not cached on the shared client.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, NotRequired, TypedDict

from chrys.kernel import Agent, AgentSession
from chrys.service.agent_middleware import ApprovalMiddleware, AskUserMiddleware
from chrys.service.agent_middleware.reminders.archive_pointer import CATALOG_POINTER_RECORD_COUNT_STATE_KEY
from chrys.service.agent_middleware.response_validation import ResponseValidationMiddleware
from chrys.service.agent_middleware.system_reminder import ReminderTurns, SystemReminderMiddleware
from chrys.service.context.compaction.last_words import LastWordsGenerator
from chrys.service.context.compaction.last_words_state import LastWordsState
from chrys.service.context.manager import ContextManager
from chrys.service.vision import image_stub_middleware_for_model

from .resources import Conversation

if TYPE_CHECKING:
    from collections.abc import Awaitable, Callable, Mapping
    from pathlib import Path

    from chrys.foundation.events.bus import EventBus
    from chrys.foundation.models.session_env import SessionEnvironment
    from chrys.foundation.retry import RetryAttemptInfo
    from chrys.kernel.client import BaseChatClient
    from chrys.kernel.middleware import ChatMiddleware
    from chrys.service.agent_middleware.injection import InjectionMiddleware
    from chrys.service.approval.judge import ApprovalJudge
    from chrys.service.approval.policy import ApprovalMode, ApprovalPolicy
    from chrys.service.approval.turn_context import TurnContextHolder
    from chrys.service.context.compaction import CompactionInfo, CompressInfo, PreCompactInfo
    from chrys.service.context.compaction.last_words import CompactionStatus
    from chrys.service.context.compaction.last_words_state import DropRoundBreakerState
    from chrys.service.context.compaction.spill import SpillQuota
    from chrys.service.hooks.manager import HookManager
    from chrys.service.profiles.agents.schema import CompactionConfig
    from chrys.service.profiles.models.schema import ModelProfile


class ContextInputs(TypedDict):
    """Explicit inputs to the conversation-owned ContextManager."""

    profile: ModelProfile
    on_usage: NotRequired[Callable[..., Any] | None]
    on_compaction: NotRequired[Callable[[CompactionInfo], Awaitable[None]] | None]
    on_pre_compact: NotRequired[Callable[[PreCompactInfo], Awaitable[None]] | None]
    on_compress: NotRequired[Callable[[CompressInfo], Awaitable[None]] | None]
    on_context_pressure: NotRequired[Callable[[str, DropRoundBreakerState, int], Awaitable[None] | None] | None]
    spill_quota: NotRequired[SpillQuota | None]
    spill_record_dir: NotRequired[Path | None]
    debug_log_dir: NotRequired[Path | None]
    compaction_config: NotRequired[CompactionConfig | None]
    include_context_management: NotRequired[bool]
    memory_text: NotRequired[str]
    warn_threshold_pct: NotRequired[float]
    session_id: NotRequired[str | None]
    parent_session_id: NotRequired[str | None]
    session_dir: NotRequired[Path | None]
    skip_local_history_for_service_context: NotRequired[bool]
    service_context_default_options: NotRequired[Mapping[str, Any] | None]


class ReminderInputs(TypedDict):
    """Explicit inputs to the conversation-owned SystemReminderMiddleware."""

    runtime: NotRequired[SessionEnvironment | None]
    max_context_tokens: NotRequired[int]
    warn_threshold_pct: NotRequired[float]
    sub_agent_names: NotRequired[list[str] | None]
    shell_tool_enabled: NotRequired[bool]
    tool_names: NotRequired[list[str] | None]
    session_root: NotRequired[Path | None]
    file_read_available: NotRequired[bool]
    spill_quota: NotRequired[SpillQuota | None]
    catalog_pointer_enabled: NotRequired[bool]
    skill_catalog_provider: NotRequired[Callable[[], str | None] | None]
    todo_state_provider: NotRequired[Callable[[], str | None] | None]
    mcp_instructions_provider: NotRequired[Callable[[], str | None] | None]
    file_change_provider: NotRequired[Callable[[], str | None] | None]


class LastWordsInputs(TypedDict):
    """Explicit inputs to the conversation-owned LastWordsGenerator."""

    profile: ModelProfile
    template: NotRequired[str]
    max_output_tokens: NotRequired[int]
    log_dir: NotRequired[Path | None]
    session_id: NotRequired[str | None]
    parent_session_id: NotRequired[str | None]
    session_dir: NotRequired[Path | None]
    max_transient_retries: NotRequired[int | None]
    publish_retry: NotRequired[Callable[[RetryAttemptInfo], Awaitable[None]] | None]
    publish_status: NotRequired[Callable[[CompactionStatus], Awaitable[None]] | None]
    report_usage: NotRequired[Callable[[Mapping[str, Any]], None] | None]


class ApprovalInputs(TypedDict):
    """Explicit inputs to the conversation-owned ApprovalMiddleware."""

    approval_policy: ApprovalPolicy
    event_bus: EventBus
    session_id: NotRequired[str | None]
    tool_kinds: NotRequired[dict[str, str] | None]
    caller_name: NotRequired[str]
    workspace_roots: NotRequired[list[str] | None]
    approval_mode: NotRequired[ApprovalMode]
    approval_judge: NotRequired[ApprovalJudge | None]
    approval_log_dir: NotRequired[Path | None]
    workspace_cwd: NotRequired[str | None]
    dev_mode: NotRequired[bool]
    hook_manager: NotRequired[HookManager | None]
    profile_name: NotRequired[str]
    session_archive_read_roots: NotRequired[list[Path] | None]
    turn_context: NotRequired[TurnContextHolder | None]


class AskUserInputs(TypedDict):
    """Explicit inputs to the conversation-owned AskUserMiddleware."""

    event_bus: EventBus
    session_id: NotRequired[str | None]
    caller_name: NotRequired[str]
    timeout_seconds: NotRequired[int | None]


@dataclass(frozen=True, slots=True)
class SharedRuntime:
    """Only Prepared-lifetime dependencies; no session-bound tool providers."""

    client: BaseChatClient
    tools: list[Any]
    providers: list[Any]
    name: str
    instructions: str
    vision: bool


@dataclass(frozen=True, slots=True)
class MainRecipe:
    """Root context/usage before injection, image, reminder, validation."""

    context: ContextInputs
    reminder: ReminderInputs
    last_words: LastWordsInputs
    injection: Callable[[], InjectionMiddleware]
    validation: Callable[[Conversation], ResponseValidationMiddleware]
    persist_recovery: Callable[[], Awaitable[bool]] | None


@dataclass(frozen=True, slots=True)
class ChildRecipe:
    """Private child context; image/reminder precede run usage/validation.

    Registration's unused template keeps its historical usage middleware;
    invocation wrappers never enter the shared client's context manager.
    """

    context: ContextInputs
    reminder: ReminderInputs
    last_words: LastWordsInputs
    registration: bool


@dataclass(slots=True)
class KernelRuntime:
    """The state owned by one conversation; the Agent borrows shared transport."""

    owner: Conversation
    agent: Agent
    context: ContextManager
    reminder: SystemReminderMiddleware
    last_words: LastWordsState
    injection: InjectionMiddleware | None = None
    validation: ResponseValidationMiddleware | None = None

    def create_session(self) -> AgentSession:
        return self.agent.create_session()


def create_context(inputs: ContextInputs) -> ContextManager:
    return ContextManager(**inputs)


def create_reminder(inputs: ReminderInputs) -> tuple[SystemReminderMiddleware, LastWordsState]:
    """Build the reminder middleware and the LAST_WORDS state it renders, on one shared turn holder."""
    turns = ReminderTurns()
    last_words = LastWordsState(
        turns,
        spill_quota=inputs.get("spill_quota"),
        session_root=inputs.get("session_root"),
        file_read_available=inputs.get("file_read_available", False),
        todo_provider=inputs.get("todo_state_provider"),
    )
    return SystemReminderMiddleware(**inputs, last_words=last_words), last_words


def restore_phase4_state(
    reminder: SystemReminderMiddleware,
    last_words: LastWordsState,
    state: Mapping[str, Any] | None,
    *,
    available_relative_paths: frozenset[str] | set[str] | None = None,
) -> None:
    """Restore persisted Phase 4 state: the LAST_WORDS slot and the catalog pointer's record count."""
    if not reminder.renders_last_words(last_words):
        raise ValueError("restore_phase4_state needs the LAST_WORDS state this reminder middleware renders")
    state = state or {}
    last_words.restore(state, available_relative_paths=available_relative_paths)
    reminder.sources.archive_pointer.restore_record_count(state.get(CATALOG_POINTER_RECORD_COUNT_STATE_KEY))


def create_runtime(
    owner: Conversation,
    shared: SharedRuntime,
    recipe: MainRecipe | ChildRecipe,
    *,
    context: ContextManager | None = None,
    injection: InjectionMiddleware | None = None,
) -> KernelRuntime:
    """Assemble fresh mutable runtime, preserving both established chat chains.

    Main build prepares context before tool/skill progress, then completes it
    here. Child opens construct context here, after the invocation skill refresh.
    When context is supplied, recipe.context is not used to create a context.
    """
    ctx = create_context(recipe.context) if context is None else context
    reminder, last_words = create_reminder(recipe.reminder)
    ctx.compaction_strategy.bind_reminder(reminder, last_words)
    if isinstance(recipe, MainRecipe) and recipe.persist_recovery is not None:
        ctx.compaction_strategy.set_recovery_persistence_callback(recipe.persist_recovery)
    generator = LastWordsGenerator(**recipe.last_words)
    owner.own(generator.aclose)
    ctx.compaction_strategy.set_last_words_generator(generator)
    validation = recipe.validation(owner) if isinstance(recipe, MainRecipe) else None
    if isinstance(recipe, MainRecipe):
        injection = owner.retain(recipe.injection() if injection is None else injection)
        injection.set_on_drained_reminders(reminder.queue_drained_injection_reminders)
    chain: list[ChatMiddleware] = []
    if isinstance(recipe, MainRecipe):
        chain.extend(ctx.middleware)
        if injection is None:
            raise RuntimeError("The main agent recipe requires injection middleware.")
        chain.append(injection)
    elif recipe.registration:
        chain.extend(ctx.middleware)
    chain.append(image_stub_middleware_for_model(vision_enabled=shared.vision))
    chain.append(reminder)
    if isinstance(recipe, MainRecipe):
        if validation is None:
            raise RuntimeError("The main agent recipe requires response validation middleware.")
        chain.append(validation)
    agent = Agent(
        client=shared.client,
        name=shared.name,
        instructions=shared.instructions,
        tools=list(shared.tools),
        context_providers=[*ctx.providers, *shared.providers],
        middleware=chain,
    )
    return owner.retain(
        KernelRuntime(
            owner=owner,
            agent=agent,
            context=ctx,
            reminder=reminder,
            last_words=last_words,
            injection=injection,
            validation=validation,
        )
    )


async def create_approval(owner: Conversation, inputs: ApprovalInputs) -> ApprovalMiddleware:
    approval = ApprovalMiddleware(**inputs)
    await owner.own_or_release(approval.close)
    return approval


def create_ask_user(owner: Conversation, inputs: AskUserInputs) -> AskUserMiddleware:
    return owner.retain(AskUserMiddleware(**inputs))


def create_validation(
    owner: Conversation, *, publish_retry: Callable[[RetryAttemptInfo], Awaitable[None]] | None
) -> ResponseValidationMiddleware:
    return owner.retain(ResponseValidationMiddleware(publish_retry=publish_retry))
