# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.

"""Chrys-owned agent kernel.

The package provides agent orchestration, the model/tool loop, middleware,
session context and history, telemetry, compaction, and tool construction
and invocation. ``types.py`` is the public facade for kernel types.

Modules in this package import only the stdlib, intra-package modules,
allowed third-party packages, and downward ``chrys.foundation.*`` modules.
Intra-package imports are relative. Service middleware imports the kernel,
so importing service code here would create a cycle.
"""

from chrys.foundation.observability.gate import TELEMETRY_GATE, configure_telemetry

from ._loop_recorder import LoopRecorder, LoopRecorderSnapshot
from .agent import Agent
from .client import (
    CONVERSATION_HANDLE_KEYS,
    BaseChatClient,
    StorageModeResolution,
    SupportsAclose,
    collect_conversation_handles,
    report_wire_progress,
    resolve_storage_mode_and_handles,
    strip_invalidated_conversation_handles,
    wire_progress_scope,
)
from .compaction import (
    CONTEXT_WINDOW_FILLED_KEY,
    EXCLUDE_REASON_KEY,
    EXCLUDED_KEY,
    GROUP_ANNOTATION_KEY,
    GROUP_ID_KEY,
    GROUP_KIND_KEY,
    SUMMARIZED_BY_SUMMARY_ID_KEY,
    SUMMARY_OF_GROUP_IDS_KEY,
    SUMMARY_OF_MESSAGE_IDS_KEY,
    TOOL_CALL_CONTENT_TYPES,
    TOOL_RESULT_CONTENT_TYPES,
    CompactionAdmissionState,
    CompactionCallContext,
    CompactionProjectionAtomicityError,
    CompactionStrategy,
    ContextOverflowSink,
    GroupKind,
    LastWordsCompleter,
    LastWordsToolCallError,
    TokenizerProtocol,
    annotate_message_groups,
    annotate_token_counts,
    apply_compaction,
    estimate_message_tokens,
    exclude_group_ids,
    in_internal_side_call,
    included_messages,
    included_token_count,
    internal_side_call_scope,
    messages_contain_tool_calls,
    project_included_messages,
    raise_if_context_window_filled,
    set_excluded,
)
from .images import is_image_content, is_image_media_type
from .instrumentation import (
    AgentTelemetryLayer,
    ChatTelemetryLayer,
)
from .loop import ConsumedInjectionMessageProbe, StallExhaustedAction, ToolLoopLayer, WireRetryPolicy
from .middleware import (
    ChatContext,
    ChatMiddleware,
    ChatMiddlewareLayer,
    ChatMiddlewarePipeline,
    FunctionInvocationContext,
    FunctionMiddleware,
    FunctionMiddlewarePipeline,
    MiddlewareSplit,
    MiddlewareTermination,
    SupportsChatInner,
    SupportsGetResponse,
    split_middleware,
)
from .sessions import (
    LOCAL_HISTORY_CONVERSATION_ID,
    AgentSession,
    ContextProvider,
    HistoryProvider,
    InMemoryHistoryProvider,
    ServiceFallbackHistoryProvider,
    SessionContext,
    is_local_history_conversation_id,
)
from .types import (
    OPENAI_OUTPUT_MESSAGE_ENVELOPE_KEY,
    RETRY_BOUNDARY_UPDATE_KEY,
    SKIP_PARSING,
    AdditionItemMismatch,
    AgentInvalidResponseException,
    AgentResponse,
    AgentResponseUpdate,
    AgentRunInputs,
    Annotation,
    ChatClientContentFilterException,
    ChatClientException,
    ChatClientInvalidRequestException,
    ChatOptions,
    ChatResponse,
    ChatResponseUpdate,
    Content,
    ContentError,
    ContinuationToken,
    FinishReason,
    FinishReasonLiteral,
    FunctionInvocationConfiguration,
    FunctionTool,
    Message,
    ResponseStream,
    Role,
    TextSpanRegion,
    ToolException,
    ToolTypes,
    UsageDetails,
    add_usage_details,
    detect_media_type_from_base64,
    is_retry_boundary_update,
    map_chat_to_agent_update,
    merge_chat_options,
    normalize_messages,
    normalize_stream_usage,
    normalize_tools,
    prepend_instructions_to_messages,
    tool,
    validate_chat_options,
    validate_tool_mode,
)

__all__ = [
    "CONTEXT_WINDOW_FILLED_KEY",
    "CONVERSATION_HANDLE_KEYS",
    "EXCLUDED_KEY",
    "EXCLUDE_REASON_KEY",
    "GROUP_ANNOTATION_KEY",
    "GROUP_ID_KEY",
    "GROUP_KIND_KEY",
    "LOCAL_HISTORY_CONVERSATION_ID",
    "OPENAI_OUTPUT_MESSAGE_ENVELOPE_KEY",
    "RETRY_BOUNDARY_UPDATE_KEY",
    "SKIP_PARSING",
    "SUMMARIZED_BY_SUMMARY_ID_KEY",
    "SUMMARY_OF_GROUP_IDS_KEY",
    "SUMMARY_OF_MESSAGE_IDS_KEY",
    "TELEMETRY_GATE",
    "TOOL_CALL_CONTENT_TYPES",
    "TOOL_RESULT_CONTENT_TYPES",
    "AdditionItemMismatch",
    "Agent",
    "AgentInvalidResponseException",
    "AgentResponse",
    "AgentResponseUpdate",
    "AgentRunInputs",
    "AgentSession",
    "AgentTelemetryLayer",
    "Annotation",
    "BaseChatClient",
    "ChatClientContentFilterException",
    "ChatClientException",
    "ChatClientInvalidRequestException",
    "ChatContext",
    "ChatMiddleware",
    "ChatMiddlewareLayer",
    "ChatMiddlewarePipeline",
    "ChatOptions",
    "ChatResponse",
    "ChatResponseUpdate",
    "ChatTelemetryLayer",
    "CompactionAdmissionState",
    "CompactionCallContext",
    "CompactionProjectionAtomicityError",
    "CompactionStrategy",
    "ConsumedInjectionMessageProbe",
    "Content",
    "ContentError",
    "ContextOverflowSink",
    "ContextProvider",
    "ContinuationToken",
    "FinishReason",
    "FinishReasonLiteral",
    "FunctionInvocationConfiguration",
    "FunctionInvocationContext",
    "FunctionMiddleware",
    "FunctionMiddlewarePipeline",
    "FunctionTool",
    "GroupKind",
    "HistoryProvider",
    "InMemoryHistoryProvider",
    "LastWordsCompleter",
    "LastWordsToolCallError",
    "LoopRecorder",
    "LoopRecorderSnapshot",
    "Message",
    "MiddlewareSplit",
    "MiddlewareTermination",
    "ResponseStream",
    "Role",
    "ServiceFallbackHistoryProvider",
    "SessionContext",
    "StallExhaustedAction",
    "StorageModeResolution",
    "SupportsAclose",
    "SupportsChatInner",
    "SupportsGetResponse",
    "TextSpanRegion",
    "TokenizerProtocol",
    "ToolException",
    "ToolLoopLayer",
    "ToolTypes",
    "UsageDetails",
    "WireRetryPolicy",
    "add_usage_details",
    "annotate_message_groups",
    "annotate_token_counts",
    "apply_compaction",
    "collect_conversation_handles",
    "configure_telemetry",
    "detect_media_type_from_base64",
    "estimate_message_tokens",
    "exclude_group_ids",
    "in_internal_side_call",
    "included_messages",
    "included_token_count",
    "internal_side_call_scope",
    "is_image_content",
    "is_image_media_type",
    "is_local_history_conversation_id",
    "is_retry_boundary_update",
    "map_chat_to_agent_update",
    "merge_chat_options",
    "messages_contain_tool_calls",
    "normalize_messages",
    "normalize_stream_usage",
    "normalize_tools",
    "prepend_instructions_to_messages",
    "project_included_messages",
    "raise_if_context_window_filled",
    "report_wire_progress",
    "resolve_storage_mode_and_handles",
    "set_excluded",
    "split_middleware",
    "strip_invalidated_conversation_handles",
    "tool",
    "validate_chat_options",
    "validate_tool_mode",
    "wire_progress_scope",
]
